### GET ALL column
GET http://localhost:5015/api/nationalities
Accept: application/json

### 

### GET Nationality by Id
GET http://localhost:5015/api/nationalities/2
Accept: application/json

### 

### DELETE Nationality by Id
DELETE http://localhost:5015/api/nationalities/2
Accept: application/json


###

### GET ALL Country
GET http://localhost:5015/api/nationalities/country
Accept: application/json

### 

### GET Country by Length
GET http://localhost:5015/api/nationalities/lengthCountry
Accept: application/json

### POST Country
POST http://localhost:5015/api/nationalities/countryAdd
Content-Type: application/json
Accept: application/json

{
    "name": "test"
}
